services:
  JudgmentsDb:
    image: kazaoki/mariadb-mroonga:10.6
    container_name: JudgmentsDb
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    healthcheck:
      test: ['CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 --password="$$(cat /run/secrets/db-password)" --silent']
      interval: 3s
      retries: 5
      start_period: 30s
    secrets:
      - db-password
    volumes:
      - ./db/database:/var/lib/mysql
      - ./db/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/sql/mroonga-log.sql:/docker-entrypoint-initdb.d/mroonga-log.sql
      - ./db/import:/mnt/import
      - ./db/mariadb.conf.d:/etc/mysql/mariadb.conf.d
    environment:
      - MYSQL_DATABASE=example
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 3306
      # - 33060
    ports:
      - "3306:3306"

secrets:
  db-password:
    file: db/password.txt